version: '3.9'

services:
  api:
    networks:
      - local
    build: .
    ports:
      - "8080:8080"
    environment:
      FOLDER_DIRECTORY: /files
    volumes:
      - holdthese:/files
volumes:
  holdthese:
    external: true
networks:
  local:
    name: local
