version: '3.9'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/holdthese
      FOLDER_DIRECTORY: /files
    volumes:
      - holdthese:/files
    depends_on:
      - database
  database:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: topsecret
      POSTGRES_DB: holdthese
volumes:
  holdthese:
    external: true