server:
  error:
    include-message: always

spring:
  datasource:
    username: postgres
    password: topsecret
    url: jdbc:postgresql://localhost:5432/holdthese
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

FOLDER_DIRECTORY: /home/cayan/Desktop
